name: Move to In progress status
on:
  workflow_dispatch:
  create:
    branches:
    branches-ignore:
      - main
      - develop

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        env:
          CURRENT_BRANCH: ${{ github.event.ref }}
        run: |
          echo $CURRENT_BRANCH
      - name: Use custom action
        uses: modolee/automate-project-card@0.1.0
        with:
          status: 'In Progress'
