name: Move to Review status
on:
  pull_request:
    branches:
      - develop

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
        EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
